// <auto-generated />
namespace RetailStore.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CategoryParendID_as_nullable_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CategoryParendID_as_nullable_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201611171811186_Category.ParendID_as_nullable_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
